### PR TITLE
(470) Unit tests

### PR DESCRIPTION
**Pull request by parisiale**
- Renaming module reference to `udes_report`;
 - exposing StockExport helper method for mocking;
 - adding trivial unit tests.

### CODE REVIEW

**Review by crwr45 — COMMENTED** [review]
Looks good.
The only thing I would like to see is more comments on  the asserts to explain what they are checking, and some more immediately understandable messages if they fail.

**Comment by parisiale** [comment]
Cool, will add.
But mind that it was on purpose, as I kept one assertion for each test, so the outcome should be clear anyway.

**Review by crwr45 — COMMENTED** [review]
The messages should be have their meanings reversed, they are shown when the assertion (and therefore the test) fails and should explain why in a way easier to read than the resulting traceback.

**Review by crwr45 — COMMENTED** [review]
The messages need their meanings inverted. The message is shown when the assertion (and therefore the test) fails, and should explain why the test has failed.

"All the assert methods (except assertRaises(), assertRaisesRegexp()) accept a msg argument that, if specified, is used as the error message on failure (see also longMessage)."
https://docs.python.org/2/library/unittest.html

**Review by crwr45 — APPROVED** [review]

**Pull request merged**
